#-----------------------------------------------------------------------------------------------------------------------
# CONFIGURATION
#-----------------------------------------------------------------------------------------------------------------------
variables:
  BUILD_ARTIFACTS_EXPIRY: 1 hour
  BUILD_COMPOSER_VERSION: 2.5
  BUILD_NODE_VERSION: 16
  TEST_CODECEPTION_ARTIFACTS_EXPIRY: 1 day


#-----------------------------------------------------------------------------------------------------------------------
# INCLUDES
#-----------------------------------------------------------------------------------------------------------------------
include:
  - .prepare/ssh.yml

#-----------------------------------------------------------------------------------------------------------------------
# ANALYSE
#-----------------------------------------------------------------------------------------------------------------------
.base-analyse:
  stage: analyse
  except:
    - schedules
    - pipelines
    - tags

#-----------------------------------------------------------------------------------------------------------------------
# BUILD
#-----------------------------------------------------------------------------------------------------------------------
.base-build:
  stage: build
  allow_failure: false
  except:
    - schedules
    - pipelines
    - tags
  artifacts:
    when: on_success
    expire_in: ${BUILD_ARTIFACTS_EXPIRY}
    untracked: true

#-----------------------------------------------------------------------------------------------------------------------
# DEPLOY
#-----------------------------------------------------------------------------------------------------------------------
.base-deploy:
  variables:
    COMPOSER_CACHE_DIR: '${CI_PROJECT_DIR}/.composer'
  except:
    - schedules
    - pipelines

.base-deploy-feature:
  stage: deploy.feature
  resource_group: $CI_COMMIT_REF_NAME
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $ENVIRONMENT_URL

.feature-branches:
  only:
    - /^release-(.*)/
    - /^feature-.*$/
    - main
  variables:
    SSH_USER: ${SSH_USER_STAGE}
    SSH_HOST: ${SSH_HOST_STAGE}

#-----------------------------------------------------------------------------------------------------------------------
# SCHEDULE
#-----------------------------------------------------------------------------------------------------------------------
.base-schedule:
  rules:
    - if: $CI_TASK == "${SCHEDULE_TASK_NAME}"
      when: always
    - when: never


#-----------------------------------------------------------------------------------------------------------------------
# TEST
#-----------------------------------------------------------------------------------------------------------------------
.base-test:
  stage: test