#-----------------------------------------------------------------------------------------------------------------------
# STAGES
#-----------------------------------------------------------------------------------------------------------------------
stages:
    - analyse

#-----------------------------------------------------------------------------------------------------------------------
# JOBS
#-----------------------------------------------------------------------------------------------------------------------
yaml:lint:
    stage: analyse
    image: pipelinecomponents/yamllint:latest
    only:
        - pipelines
    before_script:
        - yamllint --version
    script:
        - yamllint .