# Purpose:
#   Analyse job for scanning for security vulnerabilities running within a gitlab schedule
#
# Dependency:
#   Deployer task "security:check:composer:scheduled"
#
variables:
  SCHEDULE_TASK_NAME: "composer:security:check:scheduled"

analyse:composer:security:scheduled:
  stage: analyse
  extends:
    - .ssh
    - .base-schedule
  dependencies: [ ]
  variables:
    GIT_STRATEGY: fetch
  script:
    # install deployment dependencies
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts
    # run security check
    - vendor/bin/dep security:check:composer stage --notify $DEPLOYER_CONFIG_ADDITIONAL_OPTION
