# Purpose:
#   Analyse job for scanning for security vulnerabilities running within a gitlab schedule
#
# Dependency:
#   Deployer task "security:check:composer:scheduled"
#
analyse:composer:security:scheduled:
  stage: analyse
  extends:
    - .ssh
    - .base-schedule
  dependencies: [ ]
  cache:
    key: security-$CI_JOB_NAME-$CI_COMMIT_REF_NAME
    paths:
      - ${PATH_APP_DIR}/vendor/xima/xima-deployer-tools/deployer/security/
  variables:
    GIT_STRATEGY: fetch
  script:
    # install deployment dependencies
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts -d ${PATH_CI_DIR}
    # run security check
    - ${PATH_CI_DIR}/vendor/bin/dep security:check:composer stage --notify $DEPLOYER_CONFIG_ADDITIONAL_OPTION
