.build:
    stage: build
    allow_failure: false
    except:
        - schedules
        - pipelines
    artifacts:
        when: on_success
        expire_in: 1 hour
        untracked: true

build:php:
    extends: .build
    image:
        name: composer:2.4.4
        pull_policy: if-not-present
    variables:
        COMPOSER_CACHE_DIR: '${CI_PROJECT_DIR}/.composer'
    cache:
        key: composer-$CI_JOB_NAME
        paths:
            - ${CI_PROJECT_DIR}/.composer
            - ${PATH_PROJECT_DIR}/vendor/
            - ${PATH_PROJECT_DIR}/public/typo3/
            - ${PATH_PROJECT_DIR}/public/typo3conf/ext/
    artifacts:
        paths:
            - ${PATH_PROJECT_DIR}/vendor/
            - ${PATH_PROJECT_DIR}/web/typo3/
            - ${PATH_PROJECT_DIR}/web/typo3conf/ext/
    before_script:
        - composer config -g cache-dir "${CI_PROJECT_DIR}/.composer"
    script:
        - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts

build:node:
    extends: .build
    image:
        name: node:16
        pull_policy: if-not-present
    cache:
        key: assets-$CI_JOB_NAME
        paths:
            - ${PATH_PROJECT_DIR}/.npm-cache
            - ${PATH_PROJECT_DIR}/node_modules
    artifacts:
        paths:
            - ${PATH_PROJECT_DIR}/packages/xima-sitepackage/Resources/Public
    script:
#        - npm ci --prefix ${PATH_PROJECT_DIR} --cache ${PATH_PROJECT_DIR}/.npm-cache --prefer-offline
        - npm run build --prefix ${PATH_PROJECT_DIR}
