# Purpose:
#   Stop an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Sender)
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:feature:stop:
  extends:
    - .base-deploy-feature
    - .feature-branches
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
  dependencies: [ ]
  script:
    # trigger downstream pipeline
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME" --form ref=$FEATURE_STOP_DOWNSTREAM_BRANCH "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop
