# Purpose:
#   Stop an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Sender)
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:feature:stop:
  extends:
    - .base-deploy-feature
    - .feature-branches
  except:
    - schedules
    - pipelines
  dependencies: [ ]
  script:
    # install deployment dependencies
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts
    # trigger downstream pipeline
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME" --form ref=main "https://git.xima.de/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop