# Purpose:
#   Stop an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Receiver)
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:feature:stop:downstream:
  only:
    - pipelines
  extends:
    - .ssh
    - .base-deploy
    - .base-deploy-feature
    - .feature-branches
  except:
    - schedules
    - tags
  dependencies: [ ]
  variables:
    DEPLOYER_CONFIG_DATABASE_PASSWORD: $DB_PASSWORD_STAGE
  script:
    # install deployment dependencies
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts
    # stop feature
    - vendor/bin/dep feature:stop stage --feature=$UPSTREAM_BRANCH $DEPLOYER_CONFIG_ADDITIONAL_OPTION