# Purpose:
#   Stop an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Receiver)
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:feature:stop:downstream:
  extends:
    - .ssh
    - .base-deploy
    - .base-deploy-feature
    - .feature-branches
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_TAG != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
  dependencies: [ ]
  variables:
    DEPLOYER_CONFIG_DATABASE_PASSWORD: $DB_PASSWORD_STAGE
  script:
    - !reference [.check-deployment-dependencies, script]
    # stop feature
    - ${PATH_CI_DIR}/vendor/bin/dep feature:stop stage --feature=$UPSTREAM_BRANCH $DEPLOYER_CONFIG_ADDITIONAL_OPTION
