# Purpose:
#   Rollback a last deployed release
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:feature:rollback:
  extends:
    - .ssh
    - .base-deploy
    - .base-deploy-feature
    - .feature-branches
  script:
    - !reference [.check-deployment-dependencies, script]
    # rollback feature
    - ${PATH_CI_DIR}/vendor/bin/dep deploy:unlock stage --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - ${PATH_CI_DIR}/vendor/bin/dep rollback stage  --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  when: manual
