deploy:feature:stop:
  extends:
    - .base-deploy-feature
    - .feature-branches
  except:
    - schedules
    - pipelines
  dependencies: [ ]
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME" --form ref=main "https://git.xima.de/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop