# Purpose:
#   Rollback a last deployed release
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:prod:rollback:
  extends:
    - .ssh
    - .base-deploy
  stage: deploy.prod
  variables:
    SSH_USER: ${SSH_USER_PROD}
    SSH_HOST: ${SSH_HOST_PROD}
    PROD_BRANCH: main
  script:
    - !reference [.check-deployment-dependencies, script]
    # rollback prod
    - ${PATH_CI_DIR}/vendor/bin/dep deploy:unlock prod $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - ${PATH_CI_DIR}/vendor/bin/dep rollback prod $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  rules:
    - if: '$CI_COMMIT_REF_NAME == "${PROD_BRANCH}"'
  when: manual
