# Purpose:
#   Deploy an application on the production system
#
# Dependency:
#   XIMA Deployer Tools
#
deploy:prod:
  extends:
    - .ssh
    - .base-deploy
  needs:
    - build:php
    - build:node
  when: manual
  stage: deploy.prod
  variables:
    SSH_USER: ${SSH_USER_PROD}
    SSH_HOST: ${SSH_HOST_PROD}
  script:
    - !reference [.check-deployment-dependencies, script]
    # deploy prod
    - ${PATH_CI_DIR}/vendor/bin/dep deploy prod $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - ${PATH_CI_DIR}/vendor/bin/dep deploy:prod:notify prod
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
  allow_failure: false
