deploy:feature:stop:downstream:
  only:
    - pipelines
  extends:
    - .ssh
    - .base-deploy
    - .base-deploy-feature
    - .feature-branches
  except:
    - schedules
    - tags
  dependencies: [ ]
  variables:
    DEPLOYER_CONFIG_DATABASE_PASSWORD: $DB_PASSWORD_STAGE
  script:
    - vendor/bin/dep feature:stop stage --feature=$UPSTREAM_BRANCH $DEPLOYER_CONFIG_ADDITIONAL_OPTION