name: 'Linter'

on: [push, pull_request]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/yamllint:latest
    steps:
      - run: yamllint --version
      - run: yamllint -d relaxed .